"""empty message

Revision ID: adf213368aae
Revises: 
Create Date: 2021-02-09 20:26:43.871330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf213368aae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('nome_dono', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('horario_data', sa.DateTime(), nullable=False),
    sa.Column('banho', sa.Boolean(), nullable=True),
    sa.Column('tosa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
